In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf

In [10]:
mnist = tf.keras.datasets.mnist.load_data()

In [11]:
print(mnist)

((array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ...

In [16]:
print(mnist[0][0])

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [17]:
data = mnist[0][0]
print(data)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [18]:
(X_train, y_train),(X_test, y_test) = tf.keras.datasets.mnist.load_data()

In [19]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [20]:
model = tf.keras.models.Sequential()

In [21]:
model.add(tf.keras.layers.Input(shape=(28*28,)))
model.add(tf.keras.layers.Dense(units=512, activation='relu', name='Hidden1'))
model.add(tf.keras.layers.Dense(units=256, activation='relu', name='Hidden2'))
model.add(tf.keras.layers.Dense(units=10, activation='softmax', name='OutputLayer'))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Hidden1 (Dense)                 │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden2 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ OutputLayer (Dense)             │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

In [26]:
X_images = X_train.reshape((60000,28*28))

In [29]:
type((X_images[0]/255).dtype)

numpy.dtypes.Float64DType

In [30]:
X_images_norm = (X_images / 255).astype('float32')

In [32]:
X_images_test = X_test.reshape((10000,28*28))

In [33]:
X_images_test_norm = (X_images_test / 255).astype('float32')

In [34]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [36]:
model.fit(X_images_norm, y_train, epochs=40)

Epoch 1/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9766 - loss: 0.0749
Epoch 2/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9959 - loss: 0.0150
Epoch 3/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9957 - loss: 0.0139
Epoch 4/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9953 - loss: 0.0147
Epoch 5/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9967 - loss: 0.0105
Epoch 6/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9966 - loss: 0.0104
Epoch 7/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9969 - loss: 0.0097
Epoch 8/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9971 - loss: 0.0086
Epoch 9/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9973 - loss: 0.0095
Epoch 10/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9979 - loss: 0.0078
Epoch 11/40
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9981 - loss: 0.0061
Epoch 12/40
1875/1875 ━━━━━━━━

In [37]:
model.save("MNIST_20260626_15_30.keras")

In [39]:
model.evaluate(X_images_test_norm, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9822 - loss: 0.1822


[0.18221096694469452, 0.982200026512146]

In [40]:
import cv2

In [54]:
img = cv2.imread("digit4.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("IMAGE",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [55]:
resize_img = cv2.resize(img, (28,28))
resize_img = resize_img.astype('float32')
inverse_img = 255 - resize_img
inverse_img_norm = inverse_img / 255


In [56]:
result = model.predict(inverse_img_norm.reshape((1,28*28)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


In [59]:
print(result.argmax())

8


In [61]:
img = cv2.imread("digit9.png", cv2.IMREAD_GRAYSCALE)
resize_img = cv2.resize(img, (28,28))
resize_img = resize_img.astype('float32')
inverse_img = 255 - resize_img
inverse_img_norm = inverse_img / 255
result = model.predict(inverse_img_norm.reshape((1,28*28)))
print(result.argmax())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
9


In [62]:
img = cv2.imread("digit5.png", cv2.IMREAD_GRAYSCALE)
resize_img = cv2.resize(img, (28,28))
resize_img = resize_img.astype('float32')
inverse_img = 255 - resize_img
inverse_img_norm = inverse_img / 255
result = model.predict(inverse_img_norm.reshape((1,28*28)))
print(result.argmax())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
5


In [63]:
img = cv2.imread("digit3.png", cv2.IMREAD_GRAYSCALE)
resize_img = cv2.resize(img, (28,28))
resize_img = resize_img.astype('float32')
inverse_img = 255 - resize_img
inverse_img_norm = inverse_img / 255
result = model.predict(inverse_img_norm.reshape((1,28*28)))
print(result.argmax())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
3


In [64]:
img = cv2.imread("digit4_2.png", cv2.IMREAD_GRAYSCALE)
resize_img = cv2.resize(img, (28,28))
resize_img = resize_img.astype('float32')
inverse_img = 255 - resize_img
inverse_img_norm = inverse_img / 255
result = model.predict(inverse_img_norm.reshape((1,28*28)))
print(result.argmax())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
4
