In [45]:
from random import shuffle

import numpy as np
from numpy.ma.core import reshape

In [4]:
list1 = [1,2,3,4,5.]
a = np.array(list1)
print(type(list1))
print(type(a))
print(list1)
print(a)



<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5.0]
[1. 2. 3. 4. 5.]


In [6]:
list_a = [10, 20, 30]
list_b = [20, 30, 40]
print(list_a + list_b)
#벡터가 아니다

[10, 20, 30, 20, 30, 40]


In [7]:
list_a = np.array([10, 20, 30])
list_b = np.array([20, 30, 40])
print(list_a + list_b)
#벡터

[30 50 70]


In [9]:
print(a.ndim)
#property

1


In [10]:
b = np.array([[1,2,3], [4,5,6]])
b.shape

(2, 3)

In [12]:
a = np.array([10, 20, 30])
b = np.array([1,2,3])
a + b

array([11, 22, 33])

In [13]:
a - b

array([ 9, 18, 27])

In [14]:
a * b

array([10, 40, 90])

In [15]:
a / b

array([10., 10., 10.])

In [20]:
b = np.array([[10,20,30],
             [40,50,60]])
c = np.array([2,3,4])
b+c #broadcasting

array([[12, 23, 34],
       [42, 53, 64]])

In [22]:
b * c #2차원과 1차원의 벡터 계산에서 브로드캐스팅

array([[ 20,  60, 120],
       [ 80, 150, 240]])

In [24]:
print(np.zeros((100,100)))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
np.ones((100,100))*255

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]], shape=(100, 100))

In [27]:
np.full((100,100),255)

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], shape=(100, 100))

In [29]:
np.eye(10) #단위 행렬

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
np.eye(4)*10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [32]:
range(10)

range(0, 10)

In [38]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [45]:
list1:list = [i for i in range(10)]
print(list1) # list
print(list1[0]) # value

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0


In [48]:
for i in np.arange(0,5,0.2): # step 0.2
    print(i, end = "\t")

0.0	0.2	0.4	0.6000000000000001	0.8	1.0	1.2000000000000002	1.4000000000000001	1.6	1.8	2.0	2.2	2.4000000000000004	2.6	2.8000000000000003	3.0	3.2	3.4000000000000004	3.6	3.8000000000000003	4.0	4.2	4.4	4.6000000000000005	4.800000000000001	

In [49]:
np.arange(10)[1]

np.int64(1)

In [52]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [56]:
np.logspace(0,5,6)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [57]:
np.log10(np.logspace(0,5,6))

array([0., 1., 2., 3., 4., 5.])

In [58]:
np.sin(np.linspace(0,np.pi,11))

array([0.00000000e+00, 3.09016994e-01, 5.87785252e-01, 8.09016994e-01,
       9.51056516e-01, 1.00000000e+00, 9.51056516e-01, 8.09016994e-01,
       5.87785252e-01, 3.09016994e-01, 1.22464680e-16])

In [4]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [19]:
a = np.array([[1,1],[2,2],[3,3]])
b = np.insert(a, 1, 4, axis = 0)
c = np.insert(a, 1, 4, axis = 1)
print(np.shape(a))
print(a, end="\n\n")
print(np.shape(b))
print(b, end="\n\n")
print(np.shape(c))
print(c)

(3, 2)
[[1 1]
 [2 2]
 [3 3]]

(4, 2)
[[1 1]
 [4 4]
 [2 2]
 [3 3]]

(3, 3)
[[1 4 1]
 [2 4 2]
 [3 4 3]]


In [20]:
c = np.array([[1,2,3],[4,5,6]])
print(np.flip(c, axis = 1))
print(np.flip(c, axis = 0))

[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [21]:
print(np.flip(np.flip(c, axis = 1), axis = 0))

[[6 5 4]
 [3 2 1]]


In [23]:
arr_2d = np.array([[1,2,3,],[4,5,6],[7,8,9],[0,1,2]])
print(arr_2d[1: , 0:2]) # 슬라이스 연산자는 차원을 축소하지 않는다.

[[4 5]
 [7 8]
 [0 1]]


In [25]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a % 2 == 0)

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True False  True]]


In [26]:
x = np.arange(1,17).reshape(4,4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
result = x % 2 == 0
print(result)

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True False  True]]


In [28]:
[x % 2 == 0]

[array([[False,  True, False,  True],
        [False,  True, False,  True],
        [False,  True, False,  True],
        [False,  True, False,  True]])]

In [29]:
x[x % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [30]:
x[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [31]:
print(x.T)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [32]:
print(np.transpose(x))

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [34]:
y = x.T
print(y.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [52]:
d = np.array([[35,24,55],[69,19,9],[4,1,11]])
d.sort()
print(d)

[[24 35 55]
 [ 9 19 69]
 [ 1  4 11]]


In [59]:
d = np.array([[35,24,55],[69,19,9],[4,1,11]])
d.sort(axis = 0)
print(d)

[[ 4  1  9]
 [35 19 11]
 [69 24 55]]


In [79]:
d = np.array([[35,24,55],[69,19,9],[4,1,11]])
print(d)

[[35 24 55]
 [69 19  9]
 [ 4  1 11]]


In [80]:
d.sort(axis = 1)
print(np.flip(d, axis = 1))

[[55 35 24]
 [69 19  9]
 [11  4  1]]


In [82]:
d = np.array([[35,24,55],[69,19,9],[4,1,11]])
d.sort(axis = 0)
print(np.flip(d, axis = 0))

[[69 24 55]
 [35 19 11]
 [ 4  1  9]]


In [88]:
d = np.array([[35,24,55],[69,19,9],[4,1,11]])
d = d.flatten()
d.sort()
d = np.reshape(d,(3,3))
print(d)

[[ 1  4  9]
 [11 19 24]
 [35 55 69]]


In [90]:
a = np.arange(1,10).reshape(3,-1)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
b = np.full(9,3).reshape(3,-1)
print(b)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [98]:
print(np.random.randint(1,47,6))

[37 39 17  3 42 30]


In [107]:
a = np.arange(10)
np.random.shuffle(a)
print(a)

[2 1 0 8 5 7 4 6 3 9]


In [136]:
def train_test_split(a):
    divisor = int(len(a)*0.8)
    train_data = a[:divisor]
    test_data = a[divisor:]
    return (train_data, test_data)
a = np.arange(1,51)
np.random.shuffle(a)
a = np.reshape(a,(5,-1))
(train_data, test_data) = train_test_split(a)
print(f'Train : {train_data}, \n Test : {test_data}')

Train : [[28 23  6 48 10  4 14 34 41 47]
 [ 7 15 22  8 27 26 45 13 44 29]
 [37 12 25 42 33 17 20 40 39 21]
 [ 2 50 35  5 38 19 16 36 30 11]], 
 Test : [[43 32 24 49  9 46 31  3  1 18]]


In [137]:
import time

In [160]:
arr_a = np.random.rand(1000)
arr_b = np.random.rand(1000)
result = np.zeros(1000)

In [155]:
start = time.time()
for i in range(len(arr_a)):
    result[i] = arr_a[i] * arr_b[i]
end = time.time()
print('소요시간: ', end - start)

소요시간:  0.00046443939208984375


In [161]:
start = time.time()
result = arr_a * arr_b
end = time.time()
print('소요시간: ', end - start)

소요시간:  0.00010395050048828125


In [162]:
a = np.array([[1,1,-1],[2,-1,3],[1,2,1]])
b = np.array([0,9,8])
s = np.linalg.solve(a,b)
print(s)

[1. 2. 3.]


In [163]:
a = np.arange(10,18).reshape(2,-1)
b = np.arange(12).reshape(-1,4)

In [164]:
print(np.concatenate((a,b)))

[[10 11 12 13]
 [14 15 16 17]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [165]:
print(np.vstack((a,b)))

[[10 11 12 13]
 [14 15 16 17]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
