In [3]:
import numpy as np

In [4]:
list1 = [1,2,3,4,5.]
a = np.array(list1)
print(type(list1))
print(type(a))
print(list1)
print(a)



<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5.0]
[1. 2. 3. 4. 5.]


In [6]:
list_a = [10, 20, 30]
list_b = [20, 30, 40]
print(list_a + list_b)
#벡터가 아니다

[10, 20, 30, 20, 30, 40]


In [7]:
list_a = np.array([10, 20, 30])
list_b = np.array([20, 30, 40])
print(list_a + list_b)
#벡터

[30 50 70]


In [9]:
print(a.ndim)
#property

1


In [10]:
b = np.array([[1,2,3], [4,5,6]])
b.shape

(2, 3)

In [12]:
a = np.array([10, 20, 30])
b = np.array([1,2,3])
a + b

array([11, 22, 33])

In [13]:
a - b

array([ 9, 18, 27])

In [14]:
a * b

array([10, 40, 90])

In [15]:
a / b

array([10., 10., 10.])

In [20]:
b = np.array([[10,20,30],
             [40,50,60]])
c = np.array([2,3,4])
b+c #broadcasting

array([[12, 23, 34],
       [42, 53, 64]])

In [22]:
b * c #2차원과 1차원의 벡터 계산에서 브로드캐스팅

array([[ 20,  60, 120],
       [ 80, 150, 240]])

In [24]:
print(np.zeros((100,100)))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
np.ones((100,100))*255

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]], shape=(100, 100))

In [27]:
np.full((100,100),255)

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], shape=(100, 100))

In [29]:
np.eye(10) #단위 행렬

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
np.eye(4)*10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [32]:
range(10)

range(0, 10)

In [38]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [45]:
list1:list = [i for i in range(10)]
print(list1) # list
print(list1[0]) # value

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0


In [48]:
for i in np.arange(0,5,0.2): # step 0.2
    print(i, end = "\t")

0.0	0.2	0.4	0.6000000000000001	0.8	1.0	1.2000000000000002	1.4000000000000001	1.6	1.8	2.0	2.2	2.4000000000000004	2.6	2.8000000000000003	3.0	3.2	3.4000000000000004	3.6	3.8000000000000003	4.0	4.2	4.4	4.6000000000000005	4.800000000000001	

In [49]:
np.arange(10)[1]

np.int64(1)

In [52]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [56]:
np.logspace(0,5,6)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [57]:
np.log10(np.logspace(0,5,6))

array([0., 1., 2., 3., 4., 5.])

In [58]:
np.sin(np.linspace(0,np.pi,11))

array([0.00000000e+00, 3.09016994e-01, 5.87785252e-01, 8.09016994e-01,
       9.51056516e-01, 1.00000000e+00, 9.51056516e-01, 8.09016994e-01,
       5.87785252e-01, 3.09016994e-01, 1.22464680e-16])